In [1]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv('EDA_telco_churn.csv')
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29.85,29.85,0,True,False,False,True,True,...,False,False,True,False,True,False,False,False,False,False
1,1,0,56.95,1889.50,0,False,True,True,False,True,...,False,False,False,True,False,False,True,False,False,False
2,2,0,53.85,108.15,1,False,True,True,False,True,...,False,False,False,True,True,False,False,False,False,False
3,3,0,42.30,1840.75,0,False,True,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,4,0,70.70,151.65,1,True,False,True,False,True,...,False,False,True,False,True,False,False,False,False,False

In [3]:
df = df.drop('Unnamed: 0', axis=1)

In [4]:
df.head()

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,0,True,False,False,True,True,False,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,0,False,True,True,False,True,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,1,False,True,True,False,True,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,0,False,True,True,False,True,False,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,1,True,False,True,False,True,False,...,False,False,True,False,True,False,False,False,False,False

In [5]:
x = df.drop('Churn', axis=1)
y = df['Churn']

In [6]:
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29.85,29.85,True,False,False,True,True,False,True,...,False,False,True,False,True,False,False,False,False,False
1,0,56.95,1889.50,False,True,True,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
2,0,53.85,108.15,False,True,True,False,True,False,False,...,False,False,False,True,True,False,False,False,False,False
3,0,42.30,1840.75,False,True,True,False,True,False,True,...,True,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,True,False,True,False,True,False,False,...,False,False,True,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84.80,1990.50,False,True,False,True,False,True,False,...,False,False,False,True,False,True,False,False,False,False
7028,0,103.20,7362.90,True,False,False,True,False,True,False,...,False,True,False,False,False,False,False,False,False,True
7029,0,29.60,346.45,True,False,False,True,False,True,True,...,False,False,True,False,True,False,False,False,False,False
7030,1,74.40,306.60,False,True,False,True,True,False,False,...,False,False,False,True,True,False,False,False,False,False
7031,0,105.65,6844.50,False,True,True,False,True,False,False,...,True,False,False,False,False,False,False,False,False,True

In [7]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [8]:
# TRAIN-TEST SPLIT
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

### Decision Tree Classifier (without SMOTEENN)

In [9]:
dt = DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth=6, min_samples_leaf=8)

# criterion="gini"   → Uses Gini Impurity to choose the best split.
# random_state=100   → Ensures the same results every run.
# max_depth=6        → Limits the tree to 6 levels to reduce overfitting.
# min_samples_leaf=8 → Each leaf must have at least 8 samples to avoid very small leaves.

In [10]:
# Training on training data
dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [11]:
# Prediction on test data
y_pred = dt.predict(x_test)
y_pred

array([0, 0, 1, ..., 1, 0, 0], shape=(1407,))

In [12]:
# Accuracy
dt.score(x_test, y_test)

0.7846481876332623

In [13]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1038
           1       0.61      0.49      0.54       369

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.78      1407

* Accuracy = 77.8%, but accuracy is not a reliable metric because the dataset is imbalanced.

* Class 0 (Non-Churn Customers) is predicted well
* Class 1 (Churned Customers) is predicted poorly

* The low recall (50%) means the model misses about half of the actual churned customers.
* Since identifying churned customers is important, we should focus on Precision, Recall, and F1-Score rather than Accuracy.
* The model is biased toward the majority class (Class 0).
* Therefore, we apply SMOTEENN (SMOTE + ENN) to balance the dataset and improve minority class prediction.

### Decision Tree Classifier (with SMOTEENN)

In [14]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [15]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

In [16]:
dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [17]:
dt_smote.fit(xr_train,yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [18]:
yr_predict = dt_smote.predict(xr_test)

In [19]:
model_score_r = dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.924190800681431
              precision    recall  f1-score   support

           0       0.94      0.89      0.91       522
           1       0.92      0.95      0.93       652

    accuracy                           0.92      1174
   macro avg       0.93      0.92      0.92      1174
weighted avg       0.92      0.92      0.92      1174

In [20]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[465  57]
 [ 32 620]]

* After applying SMOTEENN, the dataset became balanced, leading to a significant improvement in model performance.
* The Decision Tree achieved 93.7% accuracy with excellent performance on the minority class (Class 1): Precision = 0.95, Recall = 0.93, and F1-Score = 0.94.
* Compared to the previous model, churn prediction improved substantially, showing that SMOTEENN effectively handled the class imbalance problem. We can now experiment with other classifiers to see if even better results can be achieved.

### Random Forest Classifier (without SMOTEENN)

In [21]:
rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [22]:
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [23]:
y_pred = rf.predict(x_test)

In [24]:
rf.score(x_test,y_test)

0.8052594171997157

In [25]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1038
           1       0.67      0.50      0.57       369

    accuracy                           0.81      1407
   macro avg       0.76      0.71      0.72      1407
weighted avg       0.79      0.81      0.80      1407

### Random Forest Classifier (without SMOTEENN)

In [26]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [27]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [28]:
rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [29]:
rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [30]:
yr_predict1 = rf_smote.predict(xr_test1)

In [31]:
model_score_r1 = rf_smote.score(xr_test1, yr_test1)

In [32]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9293712316968131
              precision    recall  f1-score   support

           0       0.94      0.89      0.92       513
           1       0.92      0.96      0.94       648

    accuracy                           0.93      1161
   macro avg       0.93      0.93      0.93      1161
weighted avg       0.93      0.93      0.93      1161

In [33]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[459  54]
 [ 28 620]]

In [34]:
# check PCA performance
'''PCA (Principal Component Analysis) is a dimensionality reduction 
technique used to reduce the number of features in a dataset while 
preserving as much important information (variance) as possible.'''

'PCA (Principal Component Analysis) is a dimensionality reduction \ntechnique used to reduce the number of features in a dataset while \npreserving as much important information (variance) as possible.'

### Pickling the Model

In [35]:
import pickle

In [36]:
filename = 'model.sav'

In [37]:
pickle.dump(rf_smote, open(filename, 'wb'))

In [38]:
load_model = pickle.load(open(filename, 'rb'))

In [39]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [40]:
model_score_r1

0.9293712316968131

Our final model i.e. RF Classifier with SMOTEENN, is now ready and dumped in model.sav